apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv001
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/station
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv002
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/auth
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv003
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/config
      server: 172.17.8.101

---

apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv004
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/contacts
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv005
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/insidePayment
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv006
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/order
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv007
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/payment
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv008
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/price
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv009
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/route
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv010
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/security
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv011
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/train
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv012
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/travel
      server: 172.17.8.101

---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv013
spec:
    storageClassName: nfs
    capacity:
      storage: 5Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    nfs:
      path: /var/nfs/data/user
      server: 172.17.8.101


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-station-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-auth-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-config-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-contacts-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-inside-payment-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-order-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-payment-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-price-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-route-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-security-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-train-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-travel-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts-user-mongo-pvc
spec:
  accessModes: [ "ReadWriteMany" ]
  storageClassName: nfs
  resources:
    requests:
      storage: 5Gi
